# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91bbeaac0a013b503b3a15a67521f75d26d1f02da0daff68100ec85f3a4c02094a8fe21029e42b1c1d5c44de455e9388b024204495fdef56ffdc0161e4f0e742

test:
  secret_key_base: 6cf284d738524d3cfee9f70e1caa3be3d328c2e2e5eefcad9585b7cac29b644bb12741593d9101614e0bd9676f87d78868e9c2ad34366a80f55ba881562ca4b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
